### ISSUE TITLE
Capistrano Integration fails with NoMethodError: undefined method `tty?' for #<Capistrano::Datadog::LogCapture:0x007fce14253070>

### ISSUE THREAD

**Issue by eventi** [DataDog/dogapi-rb#153]
Capistrano Version: 3.10.2 (Rake Version: 12.3.0)
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
```

bundler: failed to load command: cap (/Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/bin/cap)
NoMethodError: undefined method `tty?' for #<Capistrano::Datadog::LogCapture:0x007fce14253070>
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/logger.rb:99:in `log'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/logger.rb:154:in `debug'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/configuration/execution.rb:87:in `execute_task'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/dogapi-1.3.6/lib/capistrano/datadog.rb:28:in `block in find_and_execute_task'
  /Users/eventi/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/dogapi-1.3.6/lib/capistrano/datadog.rb:23:in `find_and_execute_task'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:45:in `each'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:34:in `execute!'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/lib/capistrano/cli/execute.rb:14:in `execute'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/gems/capistrano-2.15.9/bin/cap:4:in `<top (required)>'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/bin/cap:23:in `load'
  /Users/eventi/work/Codecademy-dev/repos/Codecademy/.bundle/ruby/2.3.0/bin/cap:23:in `<top (required)>'
```

**Comment by eventi** [comment]
Docs should specify version >= 1.9, closing
